[package]
name = "ip_sniffer"
version = "0.1.0"
authors = ["Khalid Ali <khalludi123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
